import { type Plant } from '@/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const initialPlants: Plant[] = [
  {
    id: '1',
    name: 'Monty the Monstera',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
    acquisitionDate: new Date('2023-03-15'),
    acquisitionType: 'purchased',
    price: 35,
    rootInfo: 'Roots are healthy and well-established.',
    leafInfo: 'New leaf unfurled last week. Some browning on older leaves.',
    clippingInfo: 'Took a clipping on 2023-09-01.',
    isDeceased: false,
  },
  {
    id: '2',
    name: 'Sammy the Snake Plant',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
    acquisitionDate: new Date('2022-11-20'),
    acquisitionType: 'gifted',
    rootInfo: 'Repotted in May 2023. Roots looked strong.',
    leafInfo: 'Very resilient, low maintenance.',
    clippingInfo: '',
    isDeceased: false,
  },
  {
    id: '3',
    name: 'Patty the Pothos',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
    acquisitionDate: new Date('2023-01-10'),
    acquisitionType: 'traded',
    tradeReason: 'Traded for a spider plant cutting.',
    rootInfo: 'Roots are visible through the drainage holes. Needs repotting soon.',
    leafInfo: 'Fast grower, leaves are variegated.',
    clippingInfo: 'Propagating a few clippings in water.',
    isDeceased: false,
  },
  {
    id: '4',
    name: 'Cal the Calathea',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
    acquisitionDate: new Date('2023-08-05'),
    acquisitionType: 'purchased',
    price: 25,
    rootInfo: 'Sensitive to tap water.',
    leafInfo: 'Leaves fold up at night. Requires high humidity.',
    clippingInfo: '',
    isDeceased: true,
  },
];
